
      TYPE phon_typ

        sequence 

        integer                 :: par        
        integer                 :: jj      
        double precision   :: enf
!	integer*8 :: us
!	integer*8 :: ihom

      END TYPE phon_typ

      TYPE amp_typ

        sequence 

        integer                 :: is
        integer                 :: ig     
        double precision   :: am

      END TYPE amp_typ

      TYPE ampr_typ

        sequence

        integer                 :: is
        integer                 :: ig
        real                    :: am

      END TYPE ampr_typ





